version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started 
  post_build:
    commands:
    - echo Build completed 
    - mvn package
artifacts:
  files:
  - target/ejercicio2helloname-0.0.1-SNAPSHOT.war
  - .ebextensions/**/*