version: 0.2

phases:
  build:
    commands:
      - echo build iniciado
      - mvn clean package
  post_build:
    commands:
      - echo build completed
artifacts:
  files:
    - target/ejercicio2helloname-0.0.1-SNAPSHOT.jar


